### ISSUE TITLE
Отзыв на тестовое задание

### ISSUE THREAD

**Issue by kobylyanskiy** [bedlamzd/emlid_test#1]
Максим, привет. Здорово, что ты уделил время и очень быстро справился! Код работает, но есть возможность выполнить задание еще лучше.

Во-первых, в 4 пункте не совсем корректный вывод ошибки на экран. Можно продублировать ошибку из утилиты или написать более общее сообщение) 
```
Введите имя файла: 
/
Ошибка. Нет такой директории "/"
```

Во, вторых, предлагаю воспользоваться shellcheck. (https://www.shellcheck.net) С помощью нее можно найти потенциальные проблемы и исправить уже существующие в shell скриптах. Попробуй создать GitHub Action и добавить туда его запуск, например на пуш в мастер или на создание нового Pull Request. 

Также я хотел, чтобы ты посмотрел [Shell Style Guide](https://google.github.io/styleguide/shellguide.html), чтобы сделать код более читаемым.

**Comment by bedlamzd** [comment]
Привет!
т.е. не обязательно было делать "кастомные" сообщения об ошибках, а можно было дублировать выдаваемые?

**Comment by kobylyanskiy** [comment]
Да, можно было дублировать)

**Comment by bedlamzd** [comment]
Хорошо, тогда сейчас попробую shellcheck и почитаю гайд.
Кстати, то как я обошёл проблему с read нормальное решение или стоит поискать по лучше? У меня при направлении ошибок в файл промпт тоже выводился в файл. Я так понял промпт и работает через поток ошибок и поэтому так выходит

**Comment by kobylyanskiy** [comment]
На самом деле лучше было перенаправлять вывод в поток ошибок, например `some_command 2>> "$err_path" || echo "Some error string" >&2`

**Comment by kobylyanskiy** [comment]
Также есть небольшая проблема: если попытаться создать директорию с именем "-q", а потом из скрипта попытаться поменять путь до нее, то он отработает неверно.

**Comment by bedlamzd** [comment]
Исправил скрипт согласно гайду; сделал shellcheck через actions и добавил для него бейдж; исправил проблему путания ввода пользователя с флагами для команд; переделал немного как вывод ошибок делается

**Comment by kobylyanskiy** [comment]
Окей, все классно, спасибо. Задание выполнено)

**Comment by bedlamzd** [comment]
Круто, тебе спасибо )
